### PR TITLE
fix(dataroom): responsive number counter in TransactionsOnChain section

### LINKED ISSUE #433: [Dataroom] fix: Onchain transactions counter is not responsive
### Description
This section is causing a layout overflow.

Screenshot 2024-08-05 at 16 41 03

### What should be fixed
The percentage display needs to be responsive.

### PR DESCRIPTION
**Pull request by DiogoSoaress**
## What it solves

Resolves #433

## How this PR fixes it

- Attribute responsive `font-size` to the number counter and to the text content

### CODE REVIEW

File: src/components/DataRoom/TransactionsOnChain/index.tsx [hunk 1]
```diff
@@ -19,13 +19,21 @@ const TransactionsOnChain = ({ text, link }: BaseBlock) => {
...
+            <CounterContainer percentage={percentageValue} />
+          </Grid>
+
+          <Grid item xs={12} md={6}>
+            <div className={css.content}>
+              <Typography variant="h1" className={css.contentCopy}>
+                {text}
+              </Typography>
+
+              <div className={css.linkContainer}>{link && <LinksWrapper link={link} />}</div>
```
Comment (iamacook) [inline src/components/DataRoom/TransactionsOnChain/index.tsx:33]: Nit: do we need to render the `linkContainer` if there is no `link`?

**Review by iamacook — APPROVED** [review]

File: src/components/DataRoom/TransactionsOnChain/index.tsx (hunk 1 above)
Comment (DiogoSoaress) [reply src/components/DataRoom/TransactionsOnChain/index.tsx]: Not at all. I have moved the conditionally render before `.linkContainer`
